### ISSUE TITLE
Set up staging / dev / prod infra

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/galago#123]
Basic dev -> staging -> prod setup

~Need two setups for `staging` and `prod` -- one that continues to deploy to github pages as the "prototype" version and one that deploys to galago.czgenepi.org as the "production" version.~ 

~It would be particularly helpful if we could include feature flags (e.g., `if (flags.prototype) {showBanner = true}`), but I'm not sure how big of a lift this would be.~

**Comment by oliviabholmes** [comment]
@sidneymbell can we document the uses for dev, staging, and prod. 

My understanding is...
* dev = playground for development, not shared with others
* staging = could have experimental features, not shared widely, but shared with collaborators for early feedback. contains big disclaimer 
* prod = what we link to from CZ GE; more rigorously vetted pushes; accessible to anyone

**Comment by sidneymbell** [comment]
Per conversation with @vincent-czi -- 
* No actual need for `dev` environments as easily run on a laptop / `localhost` and has no need for a server in order to demo
* Need a "comp bio experimental space" which will remain on github pages -- keep the current `deploy.sh` to push to `galago.chanzuckerberg.github.io`. Consider changing the name to something like `galago-experimental.chanzuckerberg.github.io`
* Need a "production / stable" version which will deploy to `galago.czgenepi.org` -- need to figure out where to host the static webpage

**Comment by vincent-czi** [comment]
Discussed this with Jess as well, plan is to keep both the Prod and "dev/experimental/labs" version of the app both on github pages. That way deploy is consistent and we're already used to working with it from Sidney's prior work. Two repos: galago and galago-labs (forked). Most dev work will be done on galago-labs once everything is set up. Merging to its main branch will deploy the dev version of the site, while galago will be the prod version.

**Comment by vincent-czi** [comment]
As part of this work, am also setting up basic CI/CD pipelines with GitHub Actions. Merge to main kicks off the deploy pipeline. We'll want to later come back and add some level of testing/linting in the Pipeline that applies to all PRs (all branch pushes?). See related #166 .
