### ISSUE TITLE
Change `sidenote` component to a tooltip / popover

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/galago#133]
Currently requires scrolling to see sidenotes which is obviously not ideal. These are all wrapped in a `src/components/formatters/Sidenote` component. 

swap this out for something like a tooltip instead

<img width="751" alt="image" src="https://user-images.githubusercontent.com/12618847/179092725-c2d1c10d-b316-42d5-b188-61b581915ac6.png">

**Comment by oliviabholmes** [comment]
@sidneymbell was this a ticket from design? In general, can we tag tickets that were brought up from the eng/design audits to help understand where they come from?

**Comment by sidneymbell** [comment]
Not from design, just a glaring design issue hehe. Yes, will make a new label for the design review.

**Comment by sidneymbell** [comment]
Fixed on branch `layout`
