### ISSUE TITLE
[BUG] Tree viz layout is broken for large clades -- need to adjust simulation params

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/galago#138]

**Comment by oliviabholmes** [comment]
@sidneymbell I'm not sure I understand what this one means :/ I see you self-assigned this one...should this be moved to the scientific review milestone?

**Comment by sidneymbell** [comment]
Punch list
- [ ] Size internal nodes by N polytomy tips
- [ ] Theta allocation for internal nodes does not include polytomy tips
- [ ] Polytomy tips do not get theta allocated and are not drawn
- [ ] Add scale bar
- [ ] Add `+` to indicate samples of interest, add to legend
