### ISSUE TITLE
Move demo & upload blurbs to side-by-side on landing page.

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/galago#147]
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/12618847/181346829-fc4b3764-b8b8-4f0f-b53e-442bee7f37b5.png">

**Comment by sidneymbell** [comment]
@Janeece - @vincent-czi had a nice idea of maybe having the JSON upload be in the gray box on the main landing page, and then the subsequent steps for upload live in the modal. This is nice because it also solves the problem of wanting progressive disclosure of the location drop downs that are all based on the json file.

This is extra extra nice because we realized that when folks come in via the URL from CZGE (or elsewhere), that provides the JSON but we'll still need to ask them for location and the optional metadata CSV.

**Comment by Janeece** [comment]
@sidneymbell I'll explore that idea in the designs I'm working on! I think that has potential to work nicely.

**Comment by Janeece** [comment]
**Design Changes:**
- move demo and analysis side by side
- include "upload json" only
- add footer (selection needs to be confirmed with Olivia
- Nice-to-have: add mini-footer to analysis page

**Design:**
https://www.figma.com/file/e4dRQ5KTMpI049CkXHQCb6/Galago?node-id=104%3A3222

**Screenshots:**
![Image](https://user-images.githubusercontent.com/63013360/184456278-84988cec-98f0-44ee-b36f-e1d0a6020442.png)


![Image](https://user-images.githubusercontent.com/63013360/184456305-dc11183d-903d-46b6-bb02-f39cd7c11894.png)
