### ISSUE TITLE
Make the relationship between samples of interest & case definitions clearer

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/galago#156]
<img width="734" alt="image" src="https://user-images.githubusercontent.com/12618847/181349692-3f4a9435-8666-46fc-aacb-7a6c1b09e91b.png">

**Comment by sidneymbell** [comment]
I think this is a great recommendation, but I worry that if they have a long list of variables they want to include in their case definition then the "Highlight and subset" button gets moved pretty far down.

**Comment by Janeece** [comment]
**Design link:**
https://www.figma.com/file/e4dRQ5KTMpI049CkXHQCb6/Galago?node-id=104%3A3034

**Screenshots:**
![Image](https://user-images.githubusercontent.com/63013360/184456179-7eb3e5d8-4fbd-4cad-b8ae-f9d433a450ac.png)
