### ISSUE TITLE
Add Tree Name or File Name to the "Analyze Data" dialog

### ISSUE THREAD

**Issue by Janeece** [chanzuckerberg/galago#196]
**Describe the improvement you'd like to see**
When I have opened a tree json from CZ GE, it would be nice if I could confirm that the tree I selected loaded by seeing the name or file. This would also be useful when uploading from the galago landing page. 

**Is your suggestion related to a problem? Please describe.**
When I come from an outside app (CZGE) I can't tell what, if anything, was loaded in the dialog. 

**Additional context**
- If we loaded in the values for location/pathogen, that may also serve this purpose
- we could have a generic "file loaded" or "file from CZ GE loaded" label instead of the specific name. 
- If we use the tree or file name, will it be familiar to users? CZ GE users probably won't know the tree file name since they didn't download it. 

<img width="618" alt="Screen Shot 2022-09-07 at 11 05 58 AM" src="https://user-images.githubusercontent.com/63013360/188948116-b77ea3c4-c508-4bd9-9c66-a78587b880ce.png">

**Comment by sidneymbell** [comment]
Done!
