### ISSUE TITLE
Display loaded file name next to "Select Tree JSON" button

### ISSUE THREAD

**Issue by Janeece** [chanzuckerberg/galago#197]
**Describe the improvement you'd like to see**
It would be nice if I could see the file name for the selected tree json next to the button, or a "file loaded" message"

**Is your suggestion related to a problem? Please describe.**
It may not be clear to every user that the file was successfully loaded, thought the "get started" button becoming active helps!

**Additional context**

![Screen Shot 2022-09-01 at 4 46 43 PM](https://user-images.githubusercontent.com/63013360/188948763-e79bf460-2630-435e-b88c-44c8e034df40.png)

**Comment by sidneymbell** [comment]
Done!
