### ISSUE TITLE
[Bug] Visual issues around fetch error message and long fetch URLs

### ISSUE THREAD

**Issue by vincent-czi** [chanzuckerberg/galago#199]
**Describe the bug**
A very long URL being fetched that fails writes out of the edge of the warning.

**Expected behavior**
Not obvious what expected behavior _should be_, but it looks weird to have it go out of the bounding box of the error.
- Could be that we want the error warning box to expand vertically and line wrap the URL ([see CSS `overflow-wrap`](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Text/Wrapping_Text))
- Could be we want a horizontal scrolling box that contains entirety of the URL that's embedded in the overall error box.

**To Reproduce**
1. Do a "fetch" on a very long URL that is not real, eg `http://localhost:3000/#/fetch/lorem.com/ipsumdolorsitametconsecteturadipisicingelitseddoeiusmodtemporincididuntutlaboreetdoloremagnaaliquaUtenimadminimveniamquisnostrudexercitationullamcolaborisnisiutaliquipexeacommodoconsequat`
2. Look at error box

**Screenshots**

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/89553795/189246188-4a8e1fe9-a06a-42df-bc1d-be15b381ad37.png">

---
`x` to close is way past rest of page content

<img width="2198" alt="image" src="https://user-images.githubusercontent.com/89553795/189246220-47ae471e-cdbd-4774-bf09-7e5adccd510d.png">

**Additional context**
While this is purely a visual thing, the data is still there, when these fetches go wrong they will usually have very long URLs. Most of the auto-generated hand off URLs for this sort of interaction are very long. But it's very much a nice-to-have since user can still get the info.

**Comment by sidneymbell** [comment]
Woof. Thanks, Vincent (somehow I just realized I have not been getting notifications for newly filed issues, sorry for the delayed response!). 

Since we've removed the URL from the error message for now, I'm going to close this for the time being. I'll definitely keep it in mind if we return to providing the URL (which would be nice)
