### ISSUE TITLE
Add URL-based API for taking in JSON

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/galago#2]
Similar to nextstrain.org/fetch/URL

**Comment by sidneymbell** [comment]
Could alternatively be a drag/drop, but (I assume) this would be less helpful for enabling deep linking to "see it in my tree" #3

**Comment by sidneymbell** [comment]
Thanks to @jacoblerner-czi for consulting on this ticket from a security standpoint! Takeaways:  

- This is low risk because and we're alright to proceed because we never send any data away from the galago client to anywhere else
- We should revisit this if we ever add features that send / share data from galago to somewhere else. 
- We should use a an HTTP proxy if we host a version of this on our own servers at some point in the future.

**Comment by sidneymbell** [comment]
Requirements and pointers on where to start (cc @oliviabholmes to add / adjust) -- 
* Can take in the same pre-signed URLs we use for Nextstrain
* Should have parameters for:
  * URL to tree file -->   `ingestNextstrain(path/to/treefile)` & `dispatch({type: "tree file uploaded", data: output_from_ingest_nextstrain})`. 
  * name of mrca node --> `find_leaf_by_name(name, traverse_preorder(tree))` --> `dispatch({type: "mrca clicked", data: output_from_find_leaf_by_name})`

**Comment by oliviabholmes** [comment]
@sidneymbell how are we currently ingesting JSON?

**Comment by sidneymbell** [comment]
@oliviabholmes -- currently via direct upload

**Comment by sidneymbell** [comment]
Notes from @vincent-czi -- 
* For folks coming from CZ GEN EPI, don't dump them straight into the analysis page; rather, prepopulate the upload screen modal with their json and preliminary guess as to their jurisdiction of interest (based on their DPH home jurisdiction set in cz gen epi). This allows them to also upload metadata and/or change jurisdiction of interest without requiring #162 or #161 .

**Comment by sidneymbell** [comment]
Status update: fetch is working for JSON and URL

Propose splitting the ticket to add the query params late next week (technically after launch).

**Comment by vincent-czi** [comment]
Closed as main chunk of work -- taking in the external URL JSON -- is complete. Follow up work for doing query / search params filed as #186
